version: 2
updates:
  - package-ecosystem: "pip"
    assignees:
      - pylakey
    directory: "/"
    target-branch: main
    schedule:
      interval: "daily"
    labels:
      - "pip"
      - "dependencies"

  - package-ecosystem: "github-actions"
    assignees:
      - pylakey
    directory: "/"
    target-branch: main
    schedule:
      interval: "daily"
    labels:
      - "github-actions"
      - "dependencies"